name: demo

on:
  push: 
    branches:
      - main
  
  pull_request:
    branches:
      - main

  jobs:
    bert-huggingfacce-wandb-demo:
      runs-on: ubuntu-latest

      env:
        WANDB_PROJECT: wandb demo
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        HF_TOKEN: ${{secrets.HF_TOKEN}}
        HF_REPO_ID: ${{DuckyDuck123/hindi-en-demo-model}}
        UPLOAD_TO_HF: "true"

      steps:
        - name: Checkout Repository
        - uses: actions/checkout@v4
      
        - name: Building the docker image
        - run: docker build -t bert-huggingface-wandb-demo .

        - name: Run Inference
        - run: |
            docker run --rm bert-huggingface-wandb-demo





